"""empty message

Revision ID: 0fa5aefada21
Revises: e92b61c5d999
Create Date: 2018-07-15 00:31:38.951012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fa5aefada21'
down_revision = 'e92b61c5d999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.alter_column('articles', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(u'articles_ibfk_1', 'articles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'articles_ibfk_1', 'articles', 'categories', ['category_id'], ['category_id'])
    op.alter_column('articles', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_table('categories',
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('category_id', 'article_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
