"""empty message

Revision ID: 2df539a09425
Revises: 10cbaa168bbb
Create Date: 2018-07-17 14:44:48.888000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df539a09425'
down_revision = '10cbaa168bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('article_desc', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'article_desc')
    # ### end Alembic commands ###
